# Generated by Django 5.2.7 on 2025-10-23 20:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(help_text='Name of the staff assisted', max_length=200)),
                ('staff_id', models.CharField(help_text='Staff ID number', max_length=50)),
                ('issue_reported', models.TextField(help_text='Description of the problem')),
                ('phone_number', models.CharField(help_text='Staff contact number', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SOLVED', 'Solved')], default='PENDING', help_text='Current status of the issue', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When this was recorded')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the issue was resolved', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or resolution details')),
                ('recorded_by', models.ForeignKey(help_text='ICT staff who recorded this', on_delete=django.db.models.deletion.PROTECT, related_name='support_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Record',
                'verbose_name_plural': 'Support Records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='support_rec_timesta_309c5c_idx'), models.Index(fields=['status'], name='support_rec_status_4973c6_idx'), models.Index(fields=['staff_id'], name='support_rec_staff_i_9fdf8e_idx')],
            },
        ),
    ]
