# Generated by Django 5.2.7 on 2025-10-23 20:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThermalRollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(help_text='Vendor or station name', max_length=200)),
                ('cashier_owner_name', models.CharField(help_text='Contact person (cashier/owner)', max_length=200)),
                ('quantity', models.PositiveIntegerField(help_text='Number of thermal rolls collected')),
                ('phone_number', models.CharField(help_text='Contact number', max_length=20)),
                ('signature', models.CharField(blank=True, help_text='Digital signature placeholder', max_length=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When this was recorded')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('recorded_by', models.ForeignKey(help_text='ICT staff who recorded this', on_delete=django.db.models.deletion.PROTECT, related_name='thermal_roll_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thermal Roll Record',
                'verbose_name_plural': 'Thermal Roll Records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='thermal_rol_timesta_553a37_idx'), models.Index(fields=['vendor_name'], name='thermal_rol_vendor__da6230_idx')],
            },
        ),
    ]
