# Generated by Django 5.2.7 on 2025-10-23 20:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(help_text='Person collecting/handling the asset', max_length=200)),
                ('staff_id', models.CharField(help_text='Staff ID number', max_length=50)),
                ('problem_reported', models.TextField(help_text='Reason for collection or issue with asset')),
                ('asset_type', models.CharField(help_text='Type of asset/machine', max_length=100)),
                ('division', models.CharField(help_text='Department or division', max_length=100)),
                ('phone_number', models.CharField(help_text='Contact number', max_length=20)),
                ('signature', models.CharField(blank=True, help_text='Digital signature or placeholder', max_length=200)),
                ('status', models.CharField(choices=[('IN_USE', 'In Use'), ('RETURNED', 'Returned'), ('UNDER_REPAIR', 'Under Repair')], default='IN_USE', help_text='Current status of the asset', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When this was recorded')),
                ('returned_at', models.DateTimeField(blank=True, help_text='When the asset was returned', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('recorded_by', models.ForeignKey(help_text='ICT staff who recorded this', on_delete=django.db.models.deletion.PROTECT, related_name='asset_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Record',
                'verbose_name_plural': 'Asset Records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='asset_manag_timesta_831517_idx'), models.Index(fields=['status'], name='asset_manag_status_7e1209_idx'), models.Index(fields=['staff_id'], name='asset_manag_staff_i_15ef1a_idx'), models.Index(fields=['asset_type'], name='asset_manag_asset_t_0790ee_idx')],
            },
        ),
    ]
