# Generated by Django 5.2.7 on 2025-10-23 20:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorAssistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Company or vendor name', max_length=200)),
                ('cashier_owner_name', models.CharField(help_text='Contact person (cashier/owner)', max_length=200)),
                ('problem_reported', models.TextField(help_text='Issue description')),
                ('phone_number', models.CharField(help_text='Contact number', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ONGOING', 'Ongoing'), ('RESOLVED', 'Resolved')], default='PENDING', help_text='Current status', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When this was recorded')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the issue was resolved', null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Resolution details')),
                ('resolved_by', models.ForeignKey(help_text='ICT officer who handled this', on_delete=django.db.models.deletion.PROTECT, related_name='vendor_assistance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Assistance Record',
                'verbose_name_plural': 'Vendor Assistance Records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='vendor_assi_timesta_6f483a_idx'), models.Index(fields=['status'], name='vendor_assi_status_27c429_idx'), models.Index(fields=['company_name'], name='vendor_assi_company_ffa866_idx')],
            },
        ),
    ]
